name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Build
        run: cd .. && mkdir foobar && mv ${GITHUB_REPOSITORY#*/} foobar && cd foobar && ls -la
