name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Build
        run: |
          cd ..
          git clone --recursive https://github.com/makestuff/build-template.git
          mv ${GITHUB_REPOSITORY#*/} build-template/
          mv build-template ${GITHUB_REPOSITORY#*/}
          cd ${GITHUB_REPOSITORY#*/}
          ls -la
          ./build.sh Release

      - name: Test
        run: |
          pwd
          find . -type f | sort
          cd ${GITHUB_REPOSITORY#*/}/build
          ctest -C Release --verbose
