name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Build
        run: |
          cd ..
          git init .
          git remote add origin https://github.com/makestuff/build-template.git
          git pull origin main
          ./build.sh Release

      - name: Test
        run: |
          cd build
          ctest -C Release --verbose

  build-windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Build
        run: |
          cd ..
          git init .
          git remote add origin https://github.com/makestuff/build-template.git
          git pull origin main
          .\build.cmd Release

      - name: Test
        run: |
          cd build
          ctest -C Release --verbose
